{% set data = load_setup_py_data() %}

package:
  name: c2dataviewer
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: 0
  noarch: python
  entry_points:
    - c2dv = c2dataviewer.c2dv:main

test:
  run:
    - python
  source_files:
    - test

requirements:
  host:
    - python
    - setuptools
    - pip
    
  run:
    - python
    - pyqt
    - psutil
    - pvapy
    - pyqtgraph=0.13
    # The following modules are required for viewing compressed images and
    # must be installed separately.
    #- python-blosc
    #- lz4
    #- bitshuffle
about:
  home: https://git.aps.anl.gov/C2/conda/data-viewer
  license: APS
  summary: APS C2 data viewer

